language: cpp

install:
  # Install conan
  - pip install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  - conan user

#sudo: required
#install:
#  # Install conan
#  - sudo -E pip install conan
#  # Automatic detection of your arch, compiler, etc.
#  - conan user

script:
  - mkdir _output && cd _output
  - conan install .. --build
  - cmake -H.. -B.
  - cmake --build .
  - ./bin/test_hello

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
      env:
         - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"

